// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPflSeX1eMYrIVeeo8ep77decr_jH75LM',
    appId: '1:18379059621:web:cebc9459676c732d35384c',
    messagingSenderId: '18379059621',
    projectId: 'capstone2-a9331',
    authDomain: 'capstone2-a9331.firebaseapp.com',
    storageBucket: 'capstone2-a9331.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9WCM4AkdE3x0oIgyEVqVrIqgVtncI-U',
    appId: '1:18379059621:android:227b331e8f33730035384c',
    messagingSenderId: '18379059621',
    projectId: 'capstone2-a9331',
    storageBucket: 'capstone2-a9331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-IfZcvYSLRhV1CqVF5y3simQhchAgk8',
    appId: '1:18379059621:ios:941c7fa56211aa2235384c',
    messagingSenderId: '18379059621',
    projectId: 'capstone2-a9331',
    storageBucket: 'capstone2-a9331.appspot.com',
    iosBundleId: 'com.example.capstoneDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-IfZcvYSLRhV1CqVF5y3simQhchAgk8',
    appId: '1:18379059621:ios:941c7fa56211aa2235384c',
    messagingSenderId: '18379059621',
    projectId: 'capstone2-a9331',
    storageBucket: 'capstone2-a9331.appspot.com',
    iosBundleId: 'com.example.capstoneDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPflSeX1eMYrIVeeo8ep77decr_jH75LM',
    appId: '1:18379059621:web:97e550810198922a35384c',
    messagingSenderId: '18379059621',
    projectId: 'capstone2-a9331',
    authDomain: 'capstone2-a9331.firebaseapp.com',
    storageBucket: 'capstone2-a9331.appspot.com',
  );
}
